{{- if .Values.customScript.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{- tpl ((.Files.Glob .Values.customScript.path).AsConfig) . | nindent 2 }}
{{- end }}