{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "locust-replicas.serviceAccountName" . }}
  labels:
{{ include "locust-replicas.labels" . | nindent 4 }}
{{- end -}}
